package com.david.travel_booking_system.enumsAndSets;

public enum PropertyType {
    Hotel,
    Apartment,
    Resort,
    Villa,
    Cabin,
    Cottage,
    GlampingSite,
    ServicedApartment,
    VacationHome,
    GuestHouse,
    Hostel,
    Motel,
    BandB,
    Ryokan,
    ResortVillage,
    HomeStay,
    Campground,
    CountryHouse,
    FarmStay,
    Boat,
    LuxuryTent,
    SelfCateringAccommodation,
    TinyHouse,
    Aparthotel,
    Chalet,
    Inn,
    Lodge
}
